/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';

export const REGISTER_USERNAME_REQUEST = 'REGISTER_USERNAME_REQUEST';
export const REGISTER_USERNAME_SUCCESS = 'REGISTER_USERNAME_SUCCESS';
export const REGISTER_USERNAME_FAILURE = 'REGISTER_USERNAME_FAILURE';

export const RECEIVE_BALANCE = "RECEIVE_BALANCE";

export const GET_UNUSED_ADDRESS_FAILURE = 'GET_UNUSED_ADDRESS_FAILURE';
export const GET_UNUSED_ADDRESS_REQUEST = 'GET_UNUSED_ADDRESS_REQUEST';
export const GET_UNUSED_ADDRESS_SUCCESS = 'GET_UNUSED_ADDRESS_SUCCESS';

export const CHANGE_NETWORK_FAILURE = 'CHANGE_NETWORK_FAILURE';
export const CHANGE_NETWORK_REQUEST = 'CHANGE_NETWORK_REQUEST';
export const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';

export const SET_MNEMONIC = 'SET_MNEMONIC';
export const SET_USERNAME = 'SET_USERNAME';
