/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const RECEIVE_BALANCE = "RECEIVE_BALANCE";

export const GET_UNUSED_ADDRESS_FAILURE = 'GET_UNUSED_ADDRESS_FAILURE';
export const GET_UNUSED_ADDRESS_REQUEST = 'GET_UNUSED_ADDRESS_REQUEST';
export const GET_UNUSED_ADDRESS_SUCCESS = 'GET_UNUSED_ADDRESS_SUCCESS';

export const CHANGE_NETWORK_FAILURE = 'CHANGE_NETWORK_FAILURE';
export const CHANGE_NETWORK_REQUEST = 'CHANGE_NETWORK_REQUEST';
export const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';

