export const GET_BLOCKCHAIN_CONTACTS_REQUEST = 'GET_BLOCKCHAIN_CONTACTS_REQUEST';
export const GET_BLOCKCHAIN_CONTACTS_SUCCESS = 'GET_BLOCKCHAIN_CONTACTS_SUCCESS';
export const GET_BLOCKCHAIN_CONTACTS_FAILURE = 'GET_BLOCKCHAIN_CONTACTS_FAILURE';

export const ACCEPT_BLOCKCHAIN_CONTACT_REQUEST = 'ACCEPT_BLOCKCHAIN_CONTACT_REQUEST';
export const ACCEPT_BLOCKCHAIN_CONTACT_SUCCESS = 'ACCEPT_BLOCKCHAIN_CONTACT_SUCCESS';
export const ACCEPT_BLOCKCHAIN_CONTACT_FAILURE = 'ACCEPT_BLOCKCHAIN_CONTACT_FAILURE';

export const REJECT_BLOCKCHAIN_CONTACT_REQUEST = 'REJECT_BLOCKCHAIN_CONTACT_REQUEST';
export const REJECT_BLOCKCHAIN_CONTACT_SUCCESS = 'REJECT_BLOCKCHAIN_CONTACT_SUCCESS';
export const REJECT_BLOCKCHAIN_CONTACT_FAILURE = 'REJECT_BLOCKCHAIN_CONTACT_FAILURE';

export const SEND_CONTACT_REQUEST_REQUEST = 'SEND_CONTACT_REQUEST_REQUEST';
export const SEND_CONTACT_REQUEST_SUCCESS = 'SEND_CONTACT_REQUEST_SUCCESS';
export const SEND_CONTACT_REQUEST_FAILURE = 'SEND_CONTACT_REQUEST_FAILURE';

export const GET_PENDING_CONTACT_REQUESTS_REQUEST = 'GET_PENDING_CONTACT_REQUESTS_REQUEST';
export const GET_PENDING_CONTACT_REQUESTS_SUCCESS = 'GET_PENDING_CONTACT_REQUESTS_SUCCESS';
export const GET_PENDING_CONTACT_REQUESTS_FAILURE = 'GET_PENDING_CONTACT_REQUESTS_FAILURE';
