export const SEND_CONTACT_REQUEST_REQUEST = 'SEND_CONTACT_REQUEST_REQUEST';
export const SEND_CONTACT_REQUEST_SUCCESS = 'SEND_CONTACT_REQUEST_SUCCESS';
export const SEND_CONTACT_REQUEST_FAILURE = 'SEND_CONTACT_REQUEST_FAILURE';

export const GET_PENDING_CONTACT_REQUESTS_REQUEST = 'GET_PENDING_CONTACT_REQUESTS_REQUEST';
export const GET_PENDING_CONTACT_REQUESTS_SUCCESS = 'GET_PENDING_CONTACT_REQUESTS_SUCCESS';
export const GET_PENDING_CONTACT_REQUESTS_FAILURE = 'GET_PENDING_CONTACT_REQUESTS_FAILURE';
