export const SEND_CONTACT_REQUEST_REQUEST = 'SEND_CONTACT_REQUEST_REQUEST';
export const SEND_CONTACT_REQUEST_SUCCESS = 'SEND_CONTACT_REQUEST_SUCCESS';
export const SEND_CONTACT_REQUEST_FAILURE = 'SEND_CONTACT_REQUEST_FAILURE';
