language: node_js

node_js:
  - "11"

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: eslint
      install:
        - git remote set-branches --add origin master
        - git fetch
      script: git diff --diff-filter=ACMR --name-only origin/master '*.js' | xargs npx eslint
    - stage: jest
      script: npm test
