/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const RECEIVE_BALANCE = "RECEIVE_BALANCE";
export const GET_USER_STATE_FAILURE = 'GET_USER_STATE_FAILURE';
export const GET_USER_STATE_REQUEST = 'GET_USER_STATE_REQUEST';
export const GET_USER_STATE_SUCCESS = 'GET_USER_STATE_SUCCESS';

export const GET_UNUSED_ADDRESS_FAILURE = 'GET_UNUSED_ADDRESS_FAILURE';
export const GET_UNUSED_ADDRESS_REQUEST = 'GET_UNUSED_ADDRESS_REQUEST';
export const GET_UNUSED_ADDRESS_SUCCESS = 'GET_UNUSED_ADDRESS_SUCCESS';
