/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const REGISTER_USERNAME_FAILURE = 'REGISTER_USERNAME_FAILURE';
export const REGISTER_USERNAME_REQUEST = 'REGISTER_USERNAME_REQUEST';
export const REGISTER_USERNAME_SUCCESS = 'REGISTER_USERNAME_SUCCESS';

export const GET_USER_STATE_FAILURE = 'GET_USER_STATE_FAILURE';
export const GET_USER_STATE_REQUEST = 'GET_USER_STATE_REQUEST';
export const GET_USER_STATE_SUCCESS = 'GET_USER_STATE_SUCCESS';
