/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @wolf
 */
export const INITIALIZE_RATE_SERVICE_REQUEST =
  "INITIALIZE_RATE_SERVICE_REQUEST";

export const INITIALIZE_RATE_SERVICE_SUCCESS =
  "INITIALIZE_RATE_SERVICE_SUCCESS";

export const INITIALIZE_RATE_SERVICE_FAILURE =
  "INITIALIZE_RATE_SERVICE_FAILURE";

export const GET_DASH_USD_RATE_REQUEST = "GET_DASH_USD_RATE_REQUEST";
export const GET_DASH_USD_RATE_SUCCESS = "GET_DASH_USD_RATE_SUCCESS";
export const GET_DASH_USD_RATE_FAILURE = "GET_DASH_USD_RATE_FAILURE";
