export const ADD_CONTACT = 'ADD_CONTACT'
export const CONTACT_REQUEST_SENT = 'CONTACT_REQUEST_SENT'
export const CONTACT_REQUEST_RECEIVED = 'CONTACT_REQUEST_RECEIVED'

export const CONTACT_STATES = {
  ADDED: 'ADDED',
  REQUEST_SENT: 'REQUEST_SENT',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  CONFIRMED: 'CONFIRMED',
}
