export const ADD_CONTACT = 'ADD_CONTACT';
export const CONTACT_REQUEST_SENT = 'CONTACT_REQUEST_SENT';
export const CONTACT_REQUEST_RECEIVED = 'CONTACT_REQUEST_RECEIVED';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';

export const ACCEPT_CONTACT_REQUEST = 'ACCEPT_CONTACT_REQUEST';
export const ACCEPT_CONTACT_SUCCESS = 'ACCEPT_CONTACT_SUCCESS';
export const ACCEPT_CONTACT_FAILURE = 'ACCEPT_CONTACT_FAILURE';

export const CONTACT_STATES = {
  ADDED: 'ADDED',
  REQUEST_SENT: 'REQUEST_SENT',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  CONFIRMED: 'CONFIRMED',
};
