// @flow
export const PROFILES_SEARCH_REQUEST = 'PROFILES_SEARCH_REQUEST';
export const PROFILES_SEARCH_SUCCESS = 'PROFILES_SEARCH_SUCCESS';
export const PROFILES_SEARCH_FAILURE = 'PROFILES_SEARCH_FAILURE';
