/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const SEARCH_BLOCKCHAIN_CONTACTS_REQUEST =
  'SEARCH_BLOCKCHAIN_CONTACTS_REQUEST';
export const SEARCH_BLOCKCHAIN_CONTACTS_SUCCESS =
  'SEARCH_BLOCKCHAIN_CONTACTS_SUCCESS';
export const SEARCH_BLOCKCHAIN_CONTACTS_FAILURE =
  'SEARCH_BLOCKCHAIN_CONTACTS_FAILURE';
export const ACCEPT_BLOCKCHAIN_CONTACT_REQUEST =
  'ACCEPT_BLOCKCHAIN_CONTACT_REQUEST';
export const ACCEPT_BLOCKCHAIN_CONTACT_SUCCESS =
  'ACCEPT_BLOCKCHAIN_CONTACT_SUCCESS';
export const ACCEPT_BLOCKCHAIN_CONTACT_FAILURE =
  'ACCEPT_BLOCKCHAIN_CONTACT_FAILURE';
export const REJECT_BLOCKCHAIN_CONTACT_REQUEST =
  'REJECT_BLOCKCHAIN_CONTACT_REQUEST';
export const REJECT_BLOCKCHAIN_CONTACT_SUCCESS =
  'REJECT_BLOCKCHAIN_CONTACT_SUCCESS';
export const REJECT_BLOCKCHAIN_CONTACT_FAILURE =
  'REJECT_BLOCKCHAIN_CONTACT_FAILURE';

export const CREATE_LOCAL_CONTACT = 'CREATE_LOCAL_CONTACT';
export const UPDATE_LOCAL_CONTACT = 'UPDATE_LOCAL_CONTACT';
export const DELETE_LOCAL_CONTACT = 'DELETE_LOCAL_CONTACT';

export const SEARCH_LOCAL_CONTACTS_REQUEST = 'SEARCH_LOCAL_CONTACTS_REQUEST';
export const SEARCH_LOCAL_CONTACTS_SUCCESS = 'SEARCH_LOCAL_CONTACTS_SUCCESS';
export const SEARCH_LOCAL_CONTACTS_FAILURE = 'SEARCH_LOCAL_CONTACTS_FAILURE';
