/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */
export const SEARCH_BLOCKCHAIN_CONTACTS_REQUEST =
  "SEARCH_BLOCKCHAIN_CONTACTS_REQUEST";
export const SEARCH_BLOCKCHAIN_CONTACTS_SUCCESS =
  "SEARCH_BLOCKCHAIN_CONTACTS_SUCCESS";
export const SEARCH_BLOCKCHAIN_CONTACTS_FAILURE =
  "SEARCH_BLOCKCHAIN_CONTACTS_FAILURE";

export const CREATE_LOCAL_CONTACT = "CREATE_LOCAL_CONTACT";
export const UPDATE_LOCAL_CONTACT = "UPDATE_LOCAL_CONTACT";
export const DELETE_LOCAL_CONTACT = "DELETE_LOCAL_CONTACT";

export const SEARCH_LOCAL_CONTACTS_REQUEST = "SEARCH_LOCAL_CONTACTS_REQUEST";
export const SEARCH_LOCAL_CONTACTS_SUCCESS = "SEARCH_LOCAL_CONTACTS_SUCCESS";
export const SEARCH_LOCAL_CONTACTS_FAILURE = "SEARCH_LOCAL_CONTACTS_FAILURE";
