/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */

export const MAKE_PAYMENT_TRANSACTION_REQUEST = "MAKE_PAYMENT_TRANSACTION_REQUEST";
export const MAKE_PAYMENT_TRANSACTION_SUCCESS = "MAKE_PAYMENT_TRANSACTION_SUCCESS";
export const MAKE_PAYMENT_TRANSACTION_FAILURE = "MAKE_PAYMENT_TRANSACTION_FAILURE";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";
