/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */

// This file is created to test search functionality and should be deleted
// when we will be able to search for blockchain users.
export default [
  {
    address: 'yQ8K2zYnqprfCwc5NhEJVtWAjxHPgT3uFD',
    image: 'https://dashpay-wallet-static.dash.org/team/alex_werner.png',
    name: 'Alex Werner',
    username: 'alexwerner',
    state: 'PENDING CONTACT',
  },
  {
    address: 'yBpsnTQ27DfMxukGqRLh8rbXNJ6vCaEmAe',
    image: 'https://dashpay-wallet-static.dash.org/team/codablocker.jpeg',
    name: 'Alexander Block',
    username: 'alexanderblock',
    state: 'IGNORED',
  },
  {
    address: 'yrsCJxFu9Vd2bSZPEUg65QpLfjNK8aXBA7',
    image: 'https://dashpay-wallet-static.dash.org/team/ALEXANDERCHOPAN.jpg',
    name: 'Alexander Chopan',
    username: 'alexanderchopan',
  },
  {
    address: 'yb34Vcdth62nZ9GmSwDXyYRW7aQBU5eMLT',
    image: 'https://dashpay-wallet-static.dash.org/team/alexandre.png',
    name: 'Alexandre Devilliers',
    username: 'alexandredevilliers',
  },
  {
    address: 'yKNf2knL43z6VuXCE5tWjRJmyh7QBgwTdv',
    image: 'https://dashpay-wallet-static.dash.org/team/alex_ru.jpg',
    name: 'Alex-ru',
    username: 'alex-ru',
  },
  {
    address: 'yPyhJY9dvmVuSXRzAwHL7ZjxgWK2GT5M3E',
    image: 'https://dashpay-wallet-static.dash.org/team/Alexy.jpg',
    name: 'Alexy',
    username: 'alexy',
  },
  {
    address: 'yFMKp873EPHSa5uJdNqwRArnBvCXYjyGcg',
    image: 'https://dashpay-wallet-static.dash.org/team/AndrewPodkovyrin.jpg',
    name: 'Andrew Podkovyrin',
    username: 'andrewpodkovyrin',
  },
  {
    address: 'yzDCGn7m2QZ9MTrqtuFJEVakNjK3Ypd5W6',
    image: 'https://dashpay-wallet-static.dash.org/team/andy_f.png',
    name: 'Andy Freer',
    username: 'andyfreer',
  },
  {
    address: 'ywLp94FXQY6tj5UyNs32Cdrxe7kSTMEbKG',
    image: 'https://dashpay-wallet-static.dash.org/team/angelo.jpg',
    name: 'Angelo Di Donato',
    username: 'angelodidonato',
  },
  {
    address: 'ypjrEBcmSaPxCDHAZnzFJKbRhMQ3NTf4uk',
    image: 'https://dashpay-wallet-static.dash.org/team/AntonSuprunchuk.jpg',
    name: 'Anton Suprunchuk',
    username: 'antonsuprunchuk',
  },
  {
    address: 'yQT54ewCdKVAvYxmzFWUsnEcypD6kR9S8Z',
    image: 'https://dashpay-wallet-static.dash.org/team/balu.png',
    name: 'Balu',
    username: 'balu',
  },
  {
    address: 'yXKH6u5BWygdaJUPZf8qRbwCFcQMkVrtSs',
    image: 'https://dashpay-wallet-static.dash.org/team/bob_carroll.jpg',
    name: 'Bob Carroll',
    username: 'bobcarroll',
  },
  {
    address: 'yZyNPHXev8TKFUtV6uEMnkzjbd4rD3RBcS',
    image: 'https://dashpay-wallet-static.dash.org/team/Bradley_Zastrow.jpg',
    name: 'Bradley Zastrow',
    username: 'bradleyzastrow',
  },
  {
    address: 'ydY6Gga2DF59m4ApUNrtq3fER7wbyMhsJK',
    image: 'https://dashpay-wallet-static.dash.org/team/anon.png',
    name: 'Brian Foster',
    username: 'brianfoster',
  },
  {
    address: 'yWLT463GdAqygBVkNX2DwftmSj7CUvebF5',
    image: 'https://dashpay-wallet-static.dash.org/team/ChrisAdam.png',
    name: 'Chris Adam',
    username: 'chrisadam',
  },
  {
    address: 'yKbHFtMAxSgJ8cRBNhnUkrsp7zwW26QqjL',
    image: 'https://dashpay-wallet-static.dash.org/team/cofresi.png',
    name: 'Cofresi',
    username: 'cofresi',
  },
  {
    address: 'yKqZwLrTAusHzpdD5QynXgFP8S942ecWtj',
    image: 'https://dashpay-wallet-static.dash.org/team/crowning.png',
    name: 'Crowning',
    username: 'crowning',
  },
  {
    address: 'yFGVuN5JnptSQ7xzrB48AT6qU9W2EagsLb',
    image: 'https://dashpay-wallet-static.dash.org/team/danaalibrandi.jpg',
    name: 'Dana Alibrandi',
    username: 'danaalibrandi',
  },
  {
    address: 'ywN8RPv493AjgzJrbSF7DWaKTs2HLpxMtm',
    image: 'https://dashpay-wallet-static.dash.org/team/DenisStepanov.jpg',
    name: 'Denis Stepanov',
    username: 'denisstepanov',
  },
  {
    address: 'yzTaBKme2C6DLG5ykr7A83dwRpWuqEUFZS',
    image: 'https://dashpay-wallet-static.dash.org/team/DjavidGabibiyan.jpg',
    name: 'Djavid Gabibiyan',
    username: 'djavidgabibiyan',
  },
  {
    address: 'yDN9tsW4CcGyuXLfMxpbPkhTz2daFr63Y7',
    image: 'https://dashpay-wallet-static.dash.org/team/ElizabethRobuck.jpg',
    name: 'Elizabeth Robuck',
    username: 'elizabethrobuck',
  },
  {
    address: 'ytaXbwjmN3Zfr857C4DWAz2Ks6TvenGJYF',
    image: 'https://dashpay-wallet-static.dash.org/team/Ernesto Contreras.jpg',
    name: 'Ernesto Contreras',
    username: 'ernestocontreras',
  },
  {
    address: 'ySk6eH7Y4aAGQzqcVuwjfnsvTmJ5Xxhrt2',
    image: 'https://dashpay-wallet-static.dash.org/team/evan.png',
    name: 'Evan Duffield',
    username: 'evanduffield',
  },
  {
    address: 'yKaw8tHxvdMXPsug6JR29SUNbAQWpBmrVf',
    image: 'https://dashpay-wallet-static.dash.org/team/fernando.png',
    name: 'Fernando Gutierrez',
    username: 'fernandogutierrez',
  },
  {
    address: 'yG8MdQmSxX2HCugW4wFf3kNLqjJ5rt9Vh7',
    image: 'https://dashpay-wallet-static.dash.org/team/jahr.png',
    name: 'gladcow',
    username: 'gladcow',
  },
  {
    address: 'yyDtRakcnJphNWGj5Z8v97u6HxEq24mVbM',
    image: 'https://dashpay-wallet-static.dash.org/team/GlennAustin.jpg',
    name: 'Glenn Austin',
    username: 'glennaustin',
  },
  {
    address: 'yyLXrkt7APqCbjuHZ2hngxsSNdvD8e36mV',
    image: 'https://dashpay-wallet-static.dash.org/team/HashEngineering.png',
    name: 'hashengineering',
    username: 'hashengineering',
  },
  {
    address: 'yEKkR7SsCf4DrwZTcnauNYULv3ejymxpd2',
    image: 'https://dashpay-wallet-static.dash.org/team/holger.png',
    name: 'Holger Schinzel',
    username: 'holgerschinzel',
  },
  {
    address: 'yuDRj2VkY6HQzCtTZJ9hPAb8BfXdGqNWnK',
    image: 'https://dashpay-wallet-static.dash.org/team/ivanborovkov.jpg',
    name: 'Ivan Borovkov',
    username: 'ivanborovkov',
  },
  {
    address: 'yg7EYAP6s2ZL9BXwbmKcMjNUxaVCpvHknR',
    image: 'https://dashpay-wallet-static.dash.org/team/shumkov.jpg',
    name: 'Ivan Shumkov',
    username: 'ivanshumkov',
  },
  {
    address: 'yRVqQu3eX2SGPBp6YNhWcxH789ytfCrZTz',
    image: 'https://dashpay-wallet-static.dash.org/team/essra.jpg',
    name: 'Jan Heinrich Meyer',
    username: 'janheinrichmeyer',
  },
  {
    address: 'yF9W6C3BPQLAckKgqjvVhYfUtGJSdXpHbw',
    image: 'https://dashpay-wallet-static.dash.org/team/janusz.jpg',
    name: 'Janusz Piasecki',
    username: 'januszpiasecki',
  },
  {
    address: 'yregU3NYAMDyQqT74p2FbRH9EZ8CJdKL65',
    image: 'https://dashpay-wallet-static.dash.org/team/JonKindel.jpg',
    name: 'Jon Kindel',
    username: 'jonkindel',
  },
  {
    address: 'yg3maXx62fsC7cTA9dntFyYDbMWV5qHeuR',
    image: 'https://dashpay-wallet-static.dash.org/team/joshua.jpg',
    name: 'Joshua Seigler',
    username: 'joshuaseigler',
  },
  {
    address: 'yvYy5UMjfsgQr6VtcC3NLb7R2pqXawEe8F',
    image: 'https://dashpay-wallet-static.dash.org/team/kamuela.jpg',
    name: 'Kamuela Franco',
    username: 'kamuelafranco',
  },
  {
    address: 'yp9w6BSex3VHTD8GCEYZ5Mb4nhrAdJRugP',
    image: 'https://dashpay-wallet-static.dash.org/team/kelly.jpg',
    name: 'Kelly Kopp-Schuetz',
    username: 'kellykopp-schuetz',
  },
  {
    address: 'yPefq9AuH3XR8jCp6nT7WtayMrN2J5vkKz',
    image: 'https://dashpay-wallet-static.dash.org/team/kira.jpg',
    name: 'Kira Bronskaia',
    username: 'kirabronskaia',
  },
  {
    address: 'yXRAGqEeCuVdL34S6UsBFhnJy7cajNmfvx',
    image: 'https://dashpay-wallet-static.dash.org/team/kreshnik_alidema.jpg',
    name: 'Kreshnik Alidema',
    username: 'kreshnikalidema',
  },
  {
    address: 'yb6HLf3XkudEqNTsxtnGJRAhZmP852CMDK',
    image: 'https://dashpay-wallet-static.dash.org/team/LeonWhite.jpg',
    name: 'Leon White',
    username: 'leonwhite',
  },
  {
    address: 'ydnRFx3pZm7WJ5VPjzLtCDqw6srUTYSeuE',
    image: 'https://dashpay-wallet-static.dash.org/team/MichaelSeitz.jpg',
    name: 'Michael Seitz',
    username: 'michaelseitz',
  },
  {
    address: 'yVrPL9CwdeNGJDMmWagvKcBZzk7AbnYU85',
    image: 'https://dashpay-wallet-static.dash.org/team/moo.png',
    name: 'MooCowMoo',
    username: 'moocowmoo',
  },
  {
    address: 'yjG2QSnzx3yFRfVe4NbtLgvAp96ZCuEU7h',
    image: 'https://dashpay-wallet-static.dash.org/team/nathan.jpeg',
    name: 'Nathan Marley',
    username: 'nathanmarley',
  },
  {
    address: 'yFWMbwgd3uJjZmGVCBhQyRzUaXA49NEvLP',
    image: 'https://dashpay-wallet-static.dash.org/team/OlgaGnezdyonova.jpg',
    name: 'Olga Gnezdyonova',
    username: 'olgagnezdyonova',
  },
  {
    address: 'yqzWZ2kMK58jbmREvYhD36Gr4fcsPVXden',
    image: 'https://dashpay-wallet-static.dash.org/team/OmarHamwi.png',
    name: 'Omar Hamwi',
    username: 'omarhamwi',
  },
  {
    address: 'ytjyqX65bpkHN7YwEzfuZgVUeGPmnrLh4S',
    image: 'https://dashpay-wallet-static.dash.org/team/PableLema.jpg',
    name: 'Pablo Lema',
    username: 'pablolema',
  },
  {
    address: 'yZTv86MV7ch9tSzK3rbnNAaEHLUD5W2BuQ',
    image: 'https://dashpay-wallet-static.dash.org/team/perry_sm.jpg',
    name: 'Perry Woodin',
    username: 'perrywoodin',
  },
  {
    address: 'ysx8c2aRCDHn4XZ79eU5mbgdVKuLzQrhYq',
    image: 'https://dashpay-wallet-static.dash.org/team/philipp.png',
    name: 'Philipp Engelhorn',
    username: 'philippengelhorn',
  },
  {
    address: 'yRWVYfcUxKBZFbzTs9nCr8puNgG4L7tkA5',
    image: 'https://dashpay-wallet-static.dash.org/team/quantumexplorer.jpg',
    name: 'Quantum Explorer',
    username: 'quantumexplorer',
  },
  {
    address: 'yEz2BTd4ubxmZr6JNtR5DGVqjKSPnfacw3',
    image: 'https://dashpay-wallet-static.dash.org/team/raico.jpg',
    name: 'Raico',
    username: 'raico',
  },
  {
    address: 'yN9aeZEg3PuhwVypXrq4b2T87zGvHSUWKC',
    image: 'https://dashpay-wallet-static.dash.org/team/RobertVadeBonCoeur.jpg',
    name: 'Robert VadeBonCoeur',
    username: 'robertvadeboncoeur',
  },
  {
    address: 'ysjM8QdDPKYbwpHhxJF2vqLfCG6Wrc37ze',
    image: 'https://dashpay-wallet-static.dash.org/team/robert.wiecko.jpg',
    name: 'Robert Wiecko',
    username: 'robertwiecko',
  },
  {
    address: 'yYqcZmR4puhHT5WvarBzfXNskxJS2UL8nK',
    image: 'https://dashpay-wallet-static.dash.org/team/ryan.png',
    name: 'Ryan Taylor',
    username: 'ryantaylor',
  },
  {
    address: 'yZtfTwzAL8e3YUjuWEnbCBxMH4agXQdh5R',
    image: 'https://dashpay-wallet-static.dash.org/team/SamBarbosa.jpg',
    name: 'Sam Barbosa',
    username: 'sambarbosa',
  },
  {
    address: 'yt6K4T8qc3w2QFUXbJHhrmxWV7A9MyS5ap',
    image: 'https://dashpay-wallet-static.dash.org/team/splawik21.png',
    name: 'Slawek',
    username: 'slawek',
  },
  {
    address: 'ydfhsHkwCzR6eqXuJVYNGy37tFPnv8QpSc',
    image: 'https://dashpay-wallet-static.dash.org/team/SubaRadhakrishnan.png',
    name: 'Suba Radhakrishnan',
    username: 'subaradhakrishnan',
  },
  {
    address: 'yLUkhm47sycH9VCE6Ntjw3zvbeTWuSZQfB',
    image: 'https://dashpay-wallet-static.dash.org/team/thelazier.jpeg',
    name: 'TheLazieR',
    username: 'thelazier',
  },
  {
    address: 'yJn2RKWwH46m5pQqDyXbkAN8vrEjBPSgGt',
    image: 'https://dashpay-wallet-static.dash.org/team/thephez.png',
    name: 'thephez',
    username: 'thephez',
  },
  {
    address: 'yqUFyfDLQknEtHjPgBSxaWKC32AJ4drcG7',
    image: 'https://dashpay-wallet-static.dash.org/team/tomasz.png',
    name: 'Tomasz Ludek',
    username: 'tomaszludek',
  },
  {
    address: 'ykbFN8azRUre2pfWv4hD6BwSZAYXug5jGV',
    image: 'https://dashpay-wallet-static.dash.org/team/udjinm6.png',
    name: 'UdjinM6',
    username: 'udjinm6',
  },
];
